export const LOAD_CATEGORY_START = 'LOAD_CATEGORY_START'
export const LOAD_CATEGORY_SUCCESS = 'LOAD_CATEGORY_SUCCESS'
export const LOAD_CATEGORY_ERROR = 'LOAD_CATEGORY_ERROR'

export const GET_SINGLE_CATEGORY_START = 'GET_SINGLE_CATEGORY_START'
export const GET_SINGLE_CATEGORY_SUCCESS = 'GET_SINGLE_CATEGORY_SUCCESS'
export const GET_SINGLE_CATEGORY_ERROR = 'GET_SINGLE_CATEGORY_ERROR'

