export const LOAD_LATEST_NEWS_START = 'LOAD_LATEST_NEWS_START'
export const LOAD_LATEST_NEWS_SUCCESS = 'LOAD_LATEST_NEWS_SUCCESS'
export const LOAD_LATEST_NEWS_ERROR = 'LOAD_LATEST_NEWS_ERROR'

export const GET_SINGLE_LATEST_NEWS_START = 'GET_SINGLE_LATEST_NEWS_START'
export const GET_SINGLE_LATEST_NEWS_SUCCESS = 'GET_SINGLE_LATEST_NEWS_SUCCESS'
export const GET_SINGLE_LATEST_NEWS_ERROR = 'GET_SINGLE_LATEST_NEWS_ERROR'