export const LOAD_MATTERS_START = 'LOAD_MATTERS_START'
export const LOAD_MATTERS_SUCCESS = 'LOAD_MATTERS_SUCCESS'
export const LOAD_MATTERS_ERROR = 'LOAD_MATTERS_ERROR'

export const GET_SINGLE_METTERS_START = 'GET_SINGLE_METTERS_START'
export const GET_SINGLE_METTERS_SUCCESS = 'GET_SINGLE_METTERS_SUCCESS'
export const GET_SINGLE_METTERS_ERROR = 'GET_SINGLE_METTERS_ERROR'