export const LOAD_SUBCATEGORY_START = 'LOAD_SUBCATEGORY_START'
export const LOAD_SUBCATEGORY_SUCCESS = 'LOAD_SUBCATEGORY_SUCCESS'
export const LOAD_SUBCATEGORY_ERROR = 'LOAD_SUBCATEGORY_ERROR'

export const GET_SINGLE_SUBCATEGORY_START = 'GET_SINGLE_SUBCATEGORY_START'
export const GET_SINGLE_SUBCATEGORY_SUCCESS = 'GET_SINGLE_SUBCATEGORY_SUCCESS'
export const GET_SINGLE_SUBCATEGORY_ERROR = 'GET_SINGLE_SUBCATEGORY_ERROR'